'use strict' // makes the JavaScript you write a little bit better

var gulp = require('gulp')
const Gitdown = require('gitdown');

// https://stackoverflow.com/questions/32981108/how-to-run-a-gulp-task-from-another-task

// Generate ARA without a Table of Contents for use iwth pandowc to convert to PDF
const araNoTOC = () => {
  return Gitdown
    .readFile(__dirname + '/ARA/ARA-Input.md')
    .writeFile(__dirname + '/ARA.md');
};
gulp.task(araNoTOC);

// Generate ARA with TOC
// This format with Markdown relative links [TOC-text](#toc-text-anchor) and putting
// anchors in the Markdown <a name="toc-text-anchor"></a>
// This format does not work for pandoc (anchors) to convert the ARA.md to PDF
const araTOC = async () => {
  return Gitdown
    .readFile(__dirname + '/ARA/ARA-Input-TOC.md')
    .writeFile(__dirname + '/ARA-TOC.md');
};
gulp.task(araTOC);

// Generate ARA artefacts
const ara = async () => {
  gulp.series("araTOC", "araNoTOC")();
}
gulp.task(ara)

// watch changes to the ARA files (glob) and
gulp.task('watchARA', () => {
  gulp.watch(['./ARA/*.md'], ara);
});

// watch changes to the README file (glob) and
// run gitdown task on changes
// FAILS: is it deprecated?
//   Error: watching ./.README/*: watch task has to be a function
//  (optionally generated by using gulp.parallel or gulp.series)
gulp.task('watch', () => {
  gulp.watch(['./.README/*'], ['gitdown']);
});
