'use strict' // makes the JavaScript you write a little bit better

var gulp = require('gulp')
const Gitdown = require('gitdown');

// https://stackoverflow.com/questions/32981108/how-to-run-a-gulp-task-from-another-task

// Generate ARA without a Table of Contents
const araNoTOC = () => {
  return Gitdown
    // ./.README/README.md fails saying "fileName must be an absolute path"
    // ?? config issue?  I did npm init ...

    .readFile(__dirname + '/ARA/ARA-Input.md')
    .writeFile(__dirname + '/ARA.md');
};
gulp.task(araNoTOC);

// Generate ARA with TOC
const araTOC = async () => {
  return Gitdown
    // ./.README/README.md fails saying "fileName must be an absolute path"
    // ?? config issue?  I did npm init ...

    .readFile(__dirname + '/ARA/ARA-TOC-Input.md')
    .writeFile(__dirname + '/ARA-TOC.md');
};
gulp.task(araTOC);

// Generate ARA artefacts
const ara = async () => {
  gulp.series("araTOC", "araNoTOC")();
}
gulp.task(ara)

// watch changes to the README file (glob) and
// run gitdown task on changes
gulp.task('watchARA', () => {
  gulp.watch(['./ARA/*.md'], ara);
});

// watch changes to the README file (glob) and
// run gitdown task on changes
// FAILS: is it deprecated?
//   Error: watching ./.README/*: watch task has to be a function
//  (optionally generated by using gulp.parallel or gulp.series)
gulp.task('watch', () => {
  gulp.watch(['./.README/*'], ['gitdown']);
});
