name: ARA Build
on: [push]

jobs:
  # Any checks that run pre-build
  build:
    runs-on: ubuntu-latest
    container:
      image: pandoc/latex:2.16.1
    steps:
    - uses: actions/checkout@master
    - name: Get Commit or Tag
      id: vars
      run: |
        tag="${GITHUB_SHA:0:8}"
        if [ "${GITHUB_EVENT_NAME}" == "release" ]; then
          ref="${GITHUB_REF}"
          tag=$(echo $GITHUB_REF | sed 's/refs\/tags\///g')
        fi
        echo "::set-output name=tag::$tag"
    - name: Build ARA PDF
      run: |
        apk add make git
        PDF_ENGINE=pdflatex VERSION=$RELEASE_VERSION make build
      env:
        RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
    - name: Provide pdf
      uses: actions/upload-artifact@v2
      with:
        name: ARA.pdf
        path: ARA.pdf
    - name: Build Gulp ARA PDF
      run: |
        apk add make git
        PDF_ENGINE=pdflatex VERSION=$RELEASE_VERSION make build-two
      env:
        RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
    - name: Provide Gulp PDF
      uses: actions/upload-artifact@v2
      with:
        name: ARA-gulp.pdf
        path: ARA-gulp.pdf
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ARA.pdf
    - name: convert_via_pandoc:
      runs-on: ubuntu-18.04
      steps:
        - uses: actions/checkout@v2

        - name: create file list
          id: files_list
          run: |
            echo "Lorem ipsum" > lorem_1.md  # create two example files
            echo "dolor sit amet" > lorem_2.md
            mkdir output  # create output dir
            # this will also include README.md
            echo "::set-output name=files::$(printf '"%s" ' *.md)"

        - uses: docker://pandoc/latex:2.9
          with:
            args: --output=output/result.pdf ${{ steps.files_list.outputs.files }}

        - uses: actions/upload-artifact@master
          with:
            name: output
            path: output
